# 현재는 루트 위치에 swagger.js를 이용해 자동으로 스웨거 생성중
# swagger.yaml 사용하고 있지 않음
openapi: 3.0.0
info:
  version: 1.0.0
  title: API docs
  description: API 문서
paths:
  /app/users:
    get:
      tags:
        - /app/users
      summary: "유저 전체 조회"
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/users"
components:
  schemas:
    users:
      type: object
      required:
        - nickname
        - email
        - status
      properties:
        nickname:
          type: string
          example: yubinquitous
        email:
          type: string
          example: yubinquitous@gmail.com
        status:
          type: integer
          example: 1
